"""empty message

Revision ID: d07fb32c7dbd
Revises: f8b60ea4c2fe
Create Date: 2019-09-14 15:38:44.469873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07fb32c7dbd'
down_revision = 'f8b60ea4c2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('coordinates', sa.String(length=100), nullable=True))
    op.drop_column('alert', 'coordination')
    op.add_column('user', sa.Column('coordinates', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.drop_column('user', 'Coordination')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Coordination', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'coordinates')
    op.add_column('alert', sa.Column('coordination', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('alert', 'coordinates')
    # ### end Alembic commands ###
