"""empty message

Revision ID: f8b60ea4c2fe
Revises: 1b3ec4ddac16
Create Date: 2019-09-14 14:41:32.984959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b60ea4c2fe'
down_revision = '1b3ec4ddac16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('Coordination', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('alert', 'coordination',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'coordination',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('user')
    # ### end Alembic commands ###
